/* Autogenerated by X16ImageTool */

#ifndef GFX_H
#define GFX_H

#define PALBG1_FILENAME "palbg1.bin"

#define TSBG1_FILENAME "tsbg1.bin"
#define TSBG1_TILE_COUNT 444

#define TMBG1_FILENAME "tmbg1.bin"
#define TMBG1_TILE_WIDTH 64
#define TMBG1_TILE_HEIGHT 32
#define TMBG1_PIXEL_WIDTH 512
#define TMBG1_PIXEL_HEIGHT 256
#define TMBG1_TILE_COUNT 2048

#endif
